#ifndef ECUIDENTIFICATION_H
#define ECUIDENTIFICATION_H

#include <QByteArray>
#include <QHash>
#include <QRegularExpression>
#include <QString>

namespace EcuIdentification
{
inline QString referenceForExtendedIdentifier(const QString &identifier)
{
    static const QHash<QString, QString> refs = {
        {QStringLiteral("AANMP000"), QString::fromUtf8("MNE10089 (non confirmé)")},
        {QStringLiteral("AANMP001"), QStringLiteral("MNE101040")},
        {QStringLiteral("AANMP002"), QStringLiteral("MNE101150")},
        {QStringLiteral("ABEMR002"), QStringLiteral("MNE10027")},
        {QStringLiteral("ABNMP000"), QStringLiteral("MNE10092")},
        {QStringLiteral("ABNMP002"), QStringLiteral("MNE101070")},
        {QStringLiteral("ABNMP003"), QStringLiteral("MNE101170")},
        {QStringLiteral("ABNMP005"), QString::fromUtf8("MNE101350 (non confirmé)")},
        {QStringLiteral("ABNMP006"), QStringLiteral("MNE101351")},
        {QStringLiteral("ACNMP005"), QStringLiteral("MNE101361")},
        {QStringLiteral("ABNMF030"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ABNMF032"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ACNMF024"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ACNMF026"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ACNMP001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ACNMP003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("ACNMP004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KAE6P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBACF000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBACF001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBACP001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBM6P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBM6P006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F053"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F062"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F063"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F064"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F065"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8F066"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P002"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P007"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P008"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P009"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P010"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P011"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P012"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P013"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P014"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P015"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P016"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KBP8P017"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCD8P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE6F014"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE6F018"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE6P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE6P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE6P004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F007"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F008"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8F009"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KCE8P004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KDE6F015"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KDE6F022"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KDE6P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KDE6P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGE6F021"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6F001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6F004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6F007"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6F008"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P002"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("KGM6P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAEDP000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAEDP001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7F017"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7P004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP7P006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8F019"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8F022"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8F023"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8F027"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P002"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAP8P006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDF008"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDF010"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDF011"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDF012"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDF013"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDP000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDP001"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDP002"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TAPDP003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7F016"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7P000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7P003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7P004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7P005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("TBP7P006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF002"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF003"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF004"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF005"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF006"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF007"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF008"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("EKDMF009"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("OCLIP000"), QString::fromUtf8("Référence ECU à confirmer")},
        {QStringLiteral("CNSMR000"), QStringLiteral("MKC10027 / MNE10027")},
        {QStringLiteral("CS6MB001"), QStringLiteral("MKC10117 / MKC101550")},
        {QStringLiteral("CS6MR004"), QStringLiteral("MKC101600 / MKC101960")},
        {QStringLiteral("KBACP000"), QStringLiteral("MKC101830")},
        {QStringLiteral("KBE6R003"), QStringLiteral("MKC10027")},
        {QStringLiteral("KBHBV001"), QStringLiteral("MKC104020")},
        {QStringLiteral("KBHBV002"), QStringLiteral("MKC104022")},
        {QStringLiteral("KBP8P004"), QStringLiteral("MKC101470")},
        {QStringLiteral("KBP8P005"), QStringLiteral("MKC101610")},
        {QStringLiteral("KCE6P000"), QStringLiteral("MNE10073")},
        {QStringLiteral("KCE6P002"), QStringLiteral("MNE101080")},
        {QStringLiteral("KDE6P002"), QStringLiteral("MNE10072")},
        {QStringLiteral("KDE6P004"), QStringLiteral("MNE101140")},
        {QStringLiteral("KFACV000"), QStringLiteral("MKC103930")},
        {QStringLiteral("KFACV001"), QStringLiteral("MKC104152")},
        {QStringLiteral("KFHBV004"), QStringLiteral("MKC104322")},
        {QStringLiteral("KFHHV002"), QStringLiteral("MKC103370")},
        {QStringLiteral("KLH3V005"), QStringLiteral("MKC103730")},
        {QStringLiteral("KLH3V006"), QStringLiteral("MKC104111 / MKC104112")},
        {QStringLiteral("KLH4V009"), QStringLiteral("MKC104391 / MKC104392")},
        {QStringLiteral("KLHBV002"), QStringLiteral("MKC104322")},
        {QStringLiteral("KLHCV001"), QStringLiteral("MKC104512")},
        {QStringLiteral("KRHBV005"), QStringLiteral("MKC104042")},
        {QStringLiteral("KTHBV002"), QStringLiteral("MKC104010")},
        {QStringLiteral("TAHHV003"), QStringLiteral("MKC102320")},
        {QStringLiteral("TAP8P007"), QStringLiteral("MKC101890")},
        {QStringLiteral("TCF7X005"), QStringLiteral("MKC10117")},
        {QStringLiteral("TCF8X005"), QStringLiteral("MKC101550")},
        {QStringLiteral("TFF8X000"), QStringLiteral("MKC101960")},
        {QStringLiteral("TFFSX000"), QStringLiteral("MKC101600")},
        {QStringLiteral("TFH7G031"), QString::fromUtf8("MKC104072 (modifié)")},
        {QStringLiteral("TFH7V007"), QStringLiteral("MKC104101")}
    };
    return refs.value(identifier.trimmed().toUpper());
}

inline QString extendedIdentifierFromReply(const QByteArray &response)
{
    QByteArray printable;
    printable.reserve(response.size());
    for (char c : response)
    {
        const unsigned char value = static_cast<unsigned char>(c);
        printable.append((value >= 0x20 && value <= 0x7E) ? char(value) : ' ');
    }

    const QString ascii = QString::fromLatin1(printable).toUpper();
    static const QRegularExpression pattern(QStringLiteral("([A-Z0-9]{8})"));
    const QRegularExpressionMatch match = pattern.match(ascii);
    return match.hasMatch() ? match.captured(1) : QString();
}
}

#endif // ECUIDENTIFICATION_H
